- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sqs/CamelSinkAWSSQSITCase.java
- Prevents the latch from trying to wait for longer than the test
- Ensure the embedded runner instance terminates at the end of the test
> Cleanup the AWS SQS Sink test

- tests/src/test/resources/log4j2.properties
I don't think we need to be running with this level of debug by default. IMHO, it actually makes harder to find things on the logs unless you know what you are looking for.
> Reduce log default log verbosity

- README.adoc
- tests/src/test/java/org/apache/camel/kafkaconnector/AbstractKafkaTest.java
- tests/src/test/java/org/apache/camel/kafkaconnector/ContainerUtil.java
- tests/src/test/java/org/apache/camel/kafkaconnector/TestCommon.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/ContainerLocalKafkaService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/KafkaService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/KafkaServiceFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/RemoteKafkaService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sns/CamelSinkAWSSNSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sqs/CamelSinkAWSSQSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/file/CamelSinkFileITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/http/CamelSinkHTTPITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/jms/CamelSinkJMSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/kinesis/CamelSourceAWSKinesisITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/s3/CamelSourceAWSS3ITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/sqs/CamelSourceAWSSQSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/jms/CamelSourceJMSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/timer/CamelSourceTimerITCase.java
This decouples the kafka test service from the local container and allows using an
external Kafka instance for testing. It also creates the base work to run the tests
with different different distributions of Kafka (ie.: different Kafka containers, etc)         
As a side effect of this change if also fixes issue #13
> Support using an external Kafka for the tests

- core/pom.xml
- core/src/main/java/org/apache/camel/kafkaconnector/transforms/CamelTransformSupport.java
- core/src/main/java/org/apache/camel/kafkaconnector/transforms/CamelTypeConverterTransform.java
- core/src/main/java/org/apache/camel/kafkaconnector/utils/SchemaHelper.java
- core/src/test/java/org/apache/camel/kafkaconnector/transforms/CamelTypeConverterTransformTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/utils/SchemaHelperTest.java
- parent/pom.xml
This shall address #16. It will initialize the default Camel type registry upon starting the connector. To use it, you can add the following to the `.properties` file as an example:
```
transforms=CamelTypeConverterTransformer
transforms.CamelTypeConverterTransformer.type=org.apache.camel.kafkaconnector.transforms.CamelTypeConverterTransform$Value
transforms.CamelTypeConverterTransformer.target.type = java.lang.Float
```
Whereby you can change `org.apache.camel.kafkaconnector.transforms.CamelTypeConverterTransform$Value` to convert the value of a connect record with `org.apache.camel.kafkaconnector.transforms.CamelTypeConverterTransform$Key` to convert the key of a connect record. 
`target.type` is the full qualified java name for the type you want to convert to. 
This transformer will …
> Support camel type converter

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceTask.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSourceTaskTest.java
This shall address https://github.com/apache/camel-kafka-connector/issues/32, it will try to infer the most suitable schema based on the `SchemaHelper`, as result, we aim to have consistent schema downstream
> Infer the suitable schema in the SourceTask

- core/pom.xml
- parent/pom.xml
- tests/pom.xml
- tests/src/test/java/org/apache/camel/kafkaconnector/TestCommon.java
- tests/src/test/java/org/apache/camel/kafkaconnector/clients/elasticsearch/ElasticSearchClient.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/elasticsearch/CamelElasticSearchIndexPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/elasticsearch/CamelElasticSearchPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/elasticsearch/CamelSinkElasticSearchITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/elasticsearch/transforms/ConnectRecordValueToMapTransformer.java
- tests/src/test/resources/log4j2.properties
Sending this one which includes preliminary support for ElasticSearch. This only supports the index operation with maps for now, since I don't want to commit further to this approach without some review/feedback.
To support this, I added a transformer for ElasticSearch. It's fairly basic and can be setup like this: 
```
transforms=ElasticSearchTransformer
transforms.ElasticSearchTransformer.type=org.apache.camel.kafkaconnector.converters.ElasticSearchTransformer
transforms.ElasticSearchTransformer.key=TheMapKey
```
> Adds support for ElasticSearch index operation + tests

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceConnectorConfig.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceTask.java
- core/src/main/java/org/apache/camel/kafkaconnector/utils/SchemaHelper.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSourceTaskTest.java
This address https://github.com/apache/camel-kafka-connector/issues/20, which as a result, the user can configure `camel.source.camelMessageHeaderKey` which is a camel message header key that contains a unique key, e.g: `CamelAwsKinesisPartitionKey`, which can be used as a source record key aka Kafka message key once written to Kafka
> Allow to configure a source record key from camel message header key

- tests/src/test/java/org/apache/camel/kafkaconnector/AbstractKafkaTest.java
- tests/src/test/java/org/apache/camel/kafkaconnector/ContainerUtil.java
- tests/src/test/java/org/apache/camel/kafkaconnector/TestCommon.java
- tests/src/test/java/org/apache/camel/kafkaconnector/clients/jms/JMSClient.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/KafkaService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/DefaultKafkaConnectPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/KafkaConnectPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/KafkaConnectRunner.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/KafkaConnectRunnerService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/KafkaConnectService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sns/CamelSinkAWSSNSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sqs/CamelAWSSQSPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sqs/CamelSinkAWSSQSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/elasticsearch/CamelSinkElasticSearchITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/file/CamelSinkFileITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/http/CamelSinkHTTPITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/jms/CamelSinkJMSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/kinesis/CamelSourceAWSKinesisITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/s3/CamelSourceAWSS3ITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/sqs/CamelSourceAWSSQSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/jms/CamelSourceJMSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/timer/CamelSourceTimerITCase.java
This simplifies the code and makes it possible to reuse the instance for more test cases in the same class. It also simplifies managing the order in which the connect runtime and the test infrastructure need to run.
> Convert the embeddable Kafka Connect runner to a JUnit rule

- core/src/main/assembly/package.xml
project.name contains colons and thus 
```
export CLASSPATH="$(find core/target/ -type f -name '*.jar' | grep '\-package' | tr '\n' ':')"
```
used to produce a broken CLASSPATH and the `connect-standalone.sh` commands mentioned in the docs did not work.
> Use artifactId instead of project.name to build colon-less distro paths

- tests/src/test/java/org/apache/camel/kafkaconnector/AbstractKafkaTest.java
- tests/src/test/java/org/apache/camel/kafkaconnector/PropertyUtils.java
This will be used for a later set of PRs to make it easy to run the tests using external infrastructure
> Added support for loading test properties from a properties file

- tests/src/test/java/org/apache/camel/kafkaconnector/PropertyUtils.java
- tests/src/test/java/org/apache/camel/kafkaconnector/clients/jms/JMSClient.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/jms/ArtemisContainer.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/jms/ContainerLocalService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/jms/JMSContainer.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/jms/JMSServiceFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/jms/QpidDispatchRouterContainer.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/jms/RemoteJMSService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/jms/CamelSinkJMSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/jms/CamelSourceJMSITCase.java
Along with the previous PR this allows to configure the test to use an external JMS broker for testing. This gives more flexibility on the testing without having to change the code. 
```
jms-service.instance.type=remote
jms.broker.address=amqp://url.to.a.broker:31672
```
> Added support for using an external JMS broker

- parent/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/try-it-out-locally.adoc
- docs/modules/ROOT/pages/try-it-out-on-openshift-with-strimzi.adoc
This makes sure that the heading levels are consistent with the heading
levels expected by Antora, i.e. page needs to start at heading 1 in
order to have the title set.
Makes sure that code block titles are set at the right place.
Rewords the examples, the trying out locally in particular and
structures the examples in sections.
> chore(docs): cleanup wording and syntax

- docs/modules/ROOT/pages/try-it-out-locally.adoc
The `<<...>>` syntax triggers asciidoctor to render an link to the
anchor tag, which is detected by the link checker in the build and the
build fails. This uses the `[...]` syntax to denote a placeholder
instead.
> fix(docs): replace anchor syntax for placeholder

- docs/modules/ROOT/pages/index.adoc
* The about section currently doesn't provide much brief on the **camel-kafka-connector**  hence I have modified the documentation to include a better brief on the same.
> Improve documentation for the about section

- core/pom.xml
- parent/pom.xml
- pom.xml
- tests/pom.xml
- tests/src/test/java/org/apache/camel/kafkaconnector/ConnectorPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/PluginPathHelper.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/EmbeddedKafkaService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sns/CamelAWSSNSPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sqs/CamelAWSSQSPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/cassandra/CamelCassandraPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/elasticsearch/CamelElasticSearchPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/elasticsearch/transforms/ConnectRecordValueToMapTransformer.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/file/CamelFilePropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/http/CamelHTTPPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/jms/CamelJMSPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/kinesis/CamelAWSKinesisPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/s3/CamelAWSS3PropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/sqs/CamelAWSSQSPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/jms/CamelJMSPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/timer/CamelTimerPropertyFactory.java
- tests/src/test/resources/log4j2.properties
This fixes a couple of errors in tests and adjust the code to work with the new
auto-generated connectors. It fixes most of the DelegatingClassLoader errors 
although one still remain in one scenario: ElasticSearch Rest with Java 8.
> Test code fixes for the auto-generated connectors

- examples/CamelSlackSinkConnector.properties
- tests/pom.xml
- tests/src/test/java/org/apache/camel/kafkaconnector/PluginPathHelper.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/slack/CamelSinkSlackITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/slack/CamelSlackPropertyFactory.java
Due to being manual, the test is disabled by default. The PR also includes an example for the Slack sink connector
> Adds a manual test for the Camel Slack sink connector

- tests/src/test/java/org/apache/camel/kafkaconnector/clients/cassandra/dao/TestDataDao.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/cassandra/CamelSinkCassandraITCase.java
The test was disabled due to github issue #143. This patch re-enables
the test with the required additional logic to make it functional along
with the other tests
> Re-enable Cassandra test using properties

- core/src/test/java/org/apache/camel/kafkaconnector/CamelSourceTaskTest.java
Merged last commit from @valdar with my previous refactoring. There is no sleep time and I have also removed timer `delay=0` option that adds about 30s delay or more. Now, on my machine, the whole suite runs consistently in about 8s vs 38s of previous version.
> Improved CamelSourceTaskTest

- tests/src/test/java/org/apache/camel/kafkaconnector/services/aws/AWSKinesisLocalContainerService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/aws/AWSLocalContainerService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/aws/AWSS3LocalContainerService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/elasticsearch/ElasticSearchLocalContainerService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/jms/ArtemisContainer.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/jms/QpidDispatchRouterContainer.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/StrimziContainer.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/StrimziService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/http/CamelSinkHTTPITCase.java
As an additional bonus of the cleanup, also allows running the 
containers remotely using DOCKER_TLS_VERIFY=0 DOCKER_HOST=tcp://my.docker.host.com:2375
> Removes usage of fixed hostnames in integration tests

- tests/src/test/java/org/apache/camel/kafkaconnector/PluginPathHelper.java
Core is not needed on the plugin path since test code now uses the connectors' path
> Remove core from test plugin path

- core/pom.xml
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkConnectorConfig.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkTask.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceConnectorConfig.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceTask.java
- core/src/main/java/org/apache/camel/kafkaconnector/utils/TaskHelper.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSourceTaskTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/utils/TaskHelperTest.java
- parent/pom.xml
We should not log record's payload by default, as it may contain sensitive information. Anyway it is useful to have a configuration option to enable/disable it for debugging purpose.
Proposing new boolean config named `camel.source.logPayload`.
> Add contentLogLevel task property

- docs/modules/ROOT/pages/contributing.adoc
- parent/pom.xml
- tests/pom.xml
- tests/src/test/java/org/apache/camel/kafkaconnector/PluginPathHelper.java
- tests/src/test/java/org/apache/camel/kafkaconnector/TestCommon.java
- tests/src/test/java/org/apache/camel/kafkaconnector/clients/salesforce/SalesforceCliContainer.java
- tests/src/test/java/org/apache/camel/kafkaconnector/clients/salesforce/SfdxCommand.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/salesforce/CamelSalesforcePropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/salesforce/CamelSinkSalesforceITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/salesforce/CamelSalesforcePropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/salesforce/CamelSourceSalesforceITCase.java
- tests/src/test/resources/log4j2.properties
This adds some simple integration tests for Salesforce. Not all functionality
is covered, but I think it provides an initial infrastructure for future tests.
Currently covered:
- Source: basic data consumption tests + change data capture tests
- Sink: createSObject operation
The tests do not run by default. Because the Salesforce DTOs are required and
also some setup is required on Salesforce, the tests need to be enabled using
a maven profile (-Psalesforce) along with the required properties for the test
execution (all documented on the test classes).
Once this initial setup is done, the tests can run automatically.
> Adds integration tests for Salesforce

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkTask.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
In case we have failed Camel exchanges, we throw  `ConnectException` in order to avoid the committing the offsets on failed messages and hence result of loss messages downstream. With this small modification, the task will directly shutdown upon failed exchanges and hence avoid any offsets being committed
> Throw ConnectException due to failed exchanges

- core/src/main/java/org/apache/camel/kafkaconnector/utils/CamelMainSupport.java
Relates to #159 
We log the options two times.
> Avoid logging the autoconfiguration summary from CamelMain

- tests/itests-aws/src/test/java/org/apache/camel/kafkaconnector/aws/common/AWSCommon.java
- tests/itests-aws/src/test/java/org/apache/camel/kafkaconnector/aws/kinesis/source/CamelSourceAWSKinesisITCase.java
Includes:
- Check for the stream presence before creating it
- Adjusted the code to use a different stream every test
- Removed unused test constants
- Removes unecessary sleep after deletion
> AWS Kinesis test fixes when in remote mode

- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/sink/CamelSinkAWSSQSITCase.java
Removes a bogus message that I had left while investigating an AWS v1 behavior.
> Removes debugging message

- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/clients/AWSSQSClient.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sns/sink/CamelAWSSNSPropertyFactory.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sns/sink/CamelSinkAWSSNSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/sink/CamelSinkAWSSQSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/source/CamelSourceAWSSQSITCase.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafka/StrimziService.java
- tests/itests-common/src/test/resources/log4j2.properties
Fixes a couple of edge cases on the tests: using local strimzi containers, running tests on a slow system, etc.
Also disables a flaky test on AWS SNS that needs further investigation
> Fixes for edge cases

- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/kinesis/source/CamelSourceAWSKinesisITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/s3/source/CamelSourceAWSS3ITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sns/sink/CamelSinkAWSSNSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/sink/CamelSinkAWSSQSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/source/CamelSourceAWSSQSITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/kinesis/source/CamelSourceAWSKinesisITCase.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/sink/CamelSinkCassandraITCase.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/source/CamelSourceCassandraITCase.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/AbstractKafkaTest.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafkaconnect/KafkaConnectEmbedded.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafkaconnect/KafkaConnectRunner.java
- tests/itests-elasticsearch/src/test/java/org/apache/camel/kafkaconnector/elasticsearch/sink/CamelSinkElasticSearchITCase.java
- tests/itests-file/src/test/java/org/apache/camel/kafkaconnector/file/sink/CamelSinkFileITCase.java
- tests/itests-http/src/test/java/org/apache/camel/kafkaconnector/http/sink/CamelSinkHTTPITCase.java
- tests/itests-salesforce/src/test/java/org/apache/camel/kafkaconnector/salesforce/sink/CamelSinkSalesforceITCase.java
- tests/itests-salesforce/src/test/java/org/apache/camel/kafkaconnector/salesforce/source/CamelSourceSalesforceITCase.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/sink/CamelSinkJMSITCase.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/source/CamelSourceJMSITCase.java
- tests/itests-slack/src/test/java/org/apache/camel/kafkaconnector/slack/sink/CamelSinkSlackITCase.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/sink/CamelSinkSyslogITCase.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/source/CamelSourceSyslogITCase.java
- tests/itests-timer/src/test/java/org/apache/camel/kafkaconnector/timer/source/CamelSourceTimerITCase.java
Defer the topic deletion to the JUnit extension mechanism to prevent an Exception on shutdown
> Defer topic deletion

- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/clients/CassandraClient.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/clients/dao/TestDataDao.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/clients/dao/TestResultSetConversionStrategy.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/sink/CamelSinkCassandraITCase.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/source/CamelSourceCassandraITCase.java
Adjusts the client code to use the newer Cassandra client version from
camel-cassandraql
> Fix cassandra for camel 3.5

- README.adoc
- tests/itests-mongodb/src/test/java/org/apache/camel/kafkaconnector/mongodb/services/MongoDBLocalContainerService.java
- tests/itests-mongodb/src/test/java/org/apache/camel/kafkaconnector/mongodb/services/MongoDBService.java
- tests/itests-mongodb/src/test/java/org/apache/camel/kafkaconnector/mongodb/services/RemoteMongoDBService.java
- tests/itests-mongodb/src/test/java/org/apache/camel/kafkaconnector/mongodb/sink/CamelSinkMongoDBITCase.java
- tests/itests-mongodb/src/test/java/org/apache/camel/kafkaconnector/mongodb/source/CamelSourceMongoDBITCase.java
We need to pass variable to the mongodb.host in format mongodb://user:pass@domain otherway:
[ERROR]   CamelSinkMongoDBITCase.setUp:63 » IllegalArgument The connection string is inv...
[ERROR]   CamelSourceMongoDBITCase.setUp:66 » IllegalArgument The connection string is i...
But if we pass in that format we receive mongodb://mongodb://user:pass@domain:port and:
[ERROR] Failures: 
[ERROR]   CamelSinkMongoDBITCase.testBasicSendReceive:120->runTest:100 Condition not met within timeout 30000. The connector CamelMongoDBSinkConnector did not start within a reasonable time
[ERROR] Errors: 
[ERROR]   CamelSourceMongoDBITCase.testFindAll » Timeout testFindAll() timed out after 9...
With that fix - test will pass (tested with remote mongodb)
> Fix mongodb test

- docs/modules/ROOT/pages/try-it-out-on-openshift-with-strimzi.adoc
Update the "Try it on OpenShift" doc on creating a connector instance to match the latest AWS S3 connector configuration in:
https://camel.apache.org/camel-kafka-connector/latest/connectors/camel-aws-s3-kafka-source-connector.html
> Update try-it-out-on-openshift-with-strimzi.adoc with latest AWS S3 connector config

- docs/modules/ROOT/pages/basic-concepts.adoc
Keyword change from "scalably"  to "scalable"
> Document Update

- .github/workflows/master-push-build.yml
Please do not merge yet.
Use the work-around suggested on https://github.com/actions/virtual-environments/issues/1499 to avoid connection timeout errors in the github actions
> Implement the connection timeout work-around

- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafka/StrimziContainer.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafka/StrimziService.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafka/ZookeeperContainer.java
This fixes some errors when launching the strimzi containers.
> Throttles strimzi startup to prevent resource reuse errors

- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafkaconnect/KafkaConnectRunnerService.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/utils/PropertyUtils.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/sink/CamelSinkSyslogITCase.java
The project standard is to use `org.junit.jupiter.api.Assertions` for assertions, but there are several instances where the older `org.junit.Assert` is used, in what seems to be an oversight.
This patch cleans up those usages, and standardizes them to use `org.junit.jupiter.api.Assertions`, like the rest of the project.
> Clean up usages of org.junit.Assert

- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/services/AWSRemoteService.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/services/AWSSNSLocalContainerService.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/services/AWSSQSLocalContainerService.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/services/AWSServiceFactory.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sns/sink/CamelSinkAWSSNSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/sink/CamelSinkAWSSQSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/source/CamelSourceAWSSQSITCase.java
Minor cleanup to simplifying migrating to the reusable infra in Camel when we migrate
> Do not use the wrapper test client on the AWS service classes

- camel-kafka-connector-catalog/pom.xml
- camel-kafka-connector-catalog/src/main/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalog.java
- camel-kafka-connector-catalog/src/test/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalogTest.java
> Catalog: expose an API for consuming connectors catalog metadata and options

- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/clients/AWSSDKClientUtils.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/services/AWSSQSLocalContainerService.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/services/AWSServiceFactory.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sqs/sink/CamelSinkAWSSQSITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sqs/source/CamelSourceAWSSQSITCase.java
Another cleanup to simplify moving some of the code to Camel
> Do not use the wrapper test client on the AWS v2 service classes

- archetypes/camel-kafka-connector-extensible-archetype/src/test/resources/projects/camel-timer-kafka-connector/archetype.properties
- archetypes/camel-kafka-connector-extensible-archetype/src/test/resources/projects/camel-timer-kafka-connector/goal.txt
#462 Add an integration test for the archetype, using maven archetype's built in integration-tests functionality (https://maven.apache.org/archetype/maven-archetype-plugin/integration-test-mojo.html) 
I tried getting a `reference` to work as well to test the maven archetype results against expected results, but it seems to be expecting us to generate java code and is generating a `src/main/java/null`.   Not sure how to get around that, but this at least tests whether the archetype:generate succeeds / whether the results build.
> Add an integration test for the archetype

- docs/modules/ROOT/pages/try-it-out-locally.adoc
I've been going through the examples and noticed a few things in the local doc 
- was using 0.3.0-SNAPSHOT
- was referring to connector properties files in config or examples - it looks like they exist now in docs/examples
- added formatting to plugin.path
> Changes to documents - change version from 0.3.0-SNAPSHOT, give the right location of the properties file within docs/examples

- camel-kafka-connector-catalog/src/main/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalog.java
it will allow to use several version of the catalog in the same JVM.
> Avoid usage of static for Camel Kafka Connector catalog

- docs/modules/ROOT/pages/contributing.adoc
The archetype test does not work with mvnd therefore it must be skipped
Related to #598
> Updated the mvnd command on the readme

- camel-kafka-connector-catalog/pom.xml
- camel-kafka-connector-catalog/src/main/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalog.java
- camel-kafka-connector-catalog/src/test/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalogTest.java
- it is exposing Camel Kafka APIs
- it requires then to add explicitly dependencies on kafka-clients and
connect-api as they are marked as "provided" for camel-kafka-connector
> Provide API to retrieve Basic configuration #679

- camel-kafka-connector-catalog/src/main/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalog.java
path inside bundles are always using "/", it is a resource path, not a
file path. i tis then not using a file separator.
> Avoid NPE on Windows for Catalog initialization #697

- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafka/EmbeddedKafkaService.java
The embedded Kafka needs a small adjustment, otherwise it fails to build
> Adjust the emdedded Kafka service to the updated interface from Camel 3.7

- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/kinesis/source/CamelSourceAWSKinesisITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/s3/source/CamelSourceAWSS3ITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sns/sink/CamelSinkAWSSNSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/sink/CamelSinkAWSSQSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/source/CamelSourceAWSSQSITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/kinesis/source/CamelSourceAWSKinesisITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/source/CamelSourceAWSS3ITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sqs/sink/CamelSinkAWSSQSITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sqs/source/CamelSourceAWSSQSITCase.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/AbstractKafkaTest.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafka/EmbeddedKafkaService.java
... and other small adjustments for when they do run
> Disable slow tests

- connectors/camel-kafka-connector-fix-dependencies.properties
- connectors/camel-sjms2-kafka-connector/pom.xml
- docs/modules/ROOT/pages/troubleshooting.adoc
- docs/modules/ROOT/pages/try-it-out-locally.adoc
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/resources/camel-kafka-connector-fix-dependencies.properties
Not sure if there is a better way to do this, but it works and it is much more convenient. What do you think?
> Set JMS clients scope runtime to include required dependencies in the package

- connectors/camel-cron-kafka-connector/pom.xml
> Camel-Cron connector: We need to add at least camel-quartz as dependency

- .github/workflows/ci-build.yml
- archetypes/camel-kafka-connector-extensible-archetype/src/test/resources/projects/camel-timer-kafka-connector/archetype.properties
- parent/pom.xml
- pom.xml
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/resources/camel-kafka-connector-template-pom.template
- tooling/pom.xml
I am opening this draft PR with some of the changes I had to do in order to build the project with Java 14. 
Let's not merge this one yet ... I think it needs some review because of several plugin upgrades.
> Java 14 changes

- docs/modules/ROOT/nav.adoc
- tooling/camel-kafka-connector-docs-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/docs/UpdateDocComponentsListMojo.java
- tooling/camel-kafka-connector-docs-maven-plugin/src/main/resources/nav.mvel
I thought it's useful to have connector entries in the doc nav like camel-quarkus already has. Please merge it if you find it useful.
> Add connector entries to doc nav

- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/ec2/sink/CamelSinkAWSEC2ITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/iam/sink/CamelSinkAWSIAMITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/kinesis/sink/CamelSinkAWSKinesisITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/sink/CamelSinkAWSS3ITCase.java
Let's see if this alleviates a bit the problems with fetching images as this should reduce further the fetched containers
> Added missing slow tests filter to avoid trying to run the AWS v2 test on GH actions

- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/services/RouteConfigurator.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/services/SinkRouteConfigurator.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/services/SourceRouteConfigurator.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/services/SyslogService.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/sink/CamelSinkSyslogITCase.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/source/CamelSourceSyslogITCase.java
This fixes a few false negatives related to start/stop the CamelContext in the test
> Rework the syslog integration tests to let JUnit handle camel's lifecycle in the test

- .github/workflows/ci-build.yml
- .github/workflows/daily-java-next.yml
- Jenkinsfile.jdk11
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/sink/CamelSinkCassandraITCase.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafka/EmbeddedKafkaService.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafkaconnect/KafkaConnectEmbedded.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/CamelSinkTestSupport.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/CamelSourceTestSupport.java
- tests/itests-cxf/pom.xml
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/sink/CamelSinkCXFITCase.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/sink/CamelSinkCXFPropertyFactory.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/sink/GreeterImpl.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/sink/HelloServiceImpl.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/source/CamelSourceCXFITCase.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/source/CamelSourceCXFPropertyFactory.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/source/HelloService.java
- tests/itests-ssh/src/test/java/org/apache/camel/kafkaconnector/ssh/sink/CamelSinkSshITCase.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/services/RouteConfigurator.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/services/SinkRouteConfigurator.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/services/SourceRouteConfigurator.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/services/SyslogService.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/sink/CamelSinkSyslogITCase.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/source/CamelSourceSyslogITCase.java
- Still needs #1006. 
- Does not contain the CXF tests (should we cherry-pick them?)
**Update 1**: 
- CXF is included on the PR.
**Update 2**:
- Added #1006
> Back port test fixes from master

- archetypes/camel-kafka-connector-extensible-archetype/pom.xml
The camel-timer-kafka-connector is a dependency for the camel-kafka-connector-extensible-archetype module. Adding it to guarantee we correctly list test dependencies and also ensure parallel builds by tools such as mvnd work out of the box.
> Ensure parallel builds with mvnd work on clean environments

- archetypes/camel-kafka-connector-extensible-archetype/pom.xml
The camel-timer-kafka-connector is a dependency for the camel-kafka-connector-extensible-archetype module. Adding it to guarantee we correctly list test dependencies and also ensure parallel builds by tools such as mvnd work out of the box.
> (backport) Ensure parallel builds with mvnd work on clean environments

- buildingtools/src/main/resources/camel-checkstyle-suppressions.xml
- tooling/camel-kafka-connector-generator-maven-plugin/README.adoc
- tooling/camel-kafka-connector-generator-maven-plugin/pom.xml
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/AbstractCamelKafkaConnectorMojo.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojo.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/java/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojoIT.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources-its/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojoIT/test_generate/pom.xml
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources/camel-kafka-connector-LICENSE.txt
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources/camel-kafka-connector-NOTICE.txt
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources/camel-kafka-connector-fix-dependencies.properties
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources/camel-kafka-connector-java-header.txt
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources/camel-kafka-connector-template-example-sink-properties.template
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources/camel-kafka-connector-template-example-source-properties.template
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources/template-connector-package.xml
- tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources/template-connector-pom.xml
- tooling/pom.xml
Fix #166
Initial attempt at introducing maven it to ckc maven plugin. Running the tests is time consuming, so it's intentionally not integrated with the `integration-test` build cycle by default. You can run them by:
```
mvn clean verify -Pmaven-it
```
at this moment.
> Add tests to camel-kafka-connector-generator-maven-plugin

- tests/itests-cxf/pom.xml
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/common/HelloService.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/sink/CamelSinkCXFITCase.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/sink/HelloServiceImpl.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/sink/SinkServerFactoryBeanConfigurator.java
- tests/itests-cxf/src/test/java/org/apache/camel/kafkaconnector/cxf/source/CamelSourceCXFITCase.java
- tests/itests-cxf/src/test/resources/hello-service-test.xml
- tests/itests-cxf/src/test/resources/jaxws-test.xml
- Move common test code to a common package
- Remove exception handling code
- Move the request to separate files
> Convert the CXF sink test case to use the base Sink test class

- tests/itests-netty/src/test/java/org/apache/camel/kafkaconnector/netty/sink/CamelSinkNettyITCase.java
- tests/itests-netty/src/test/java/org/apache/camel/kafkaconnector/netty/source/CamelSourceNettyITCase.java
- avoid per class lifecycle since it seems to cause the code to try to bind the same port multiple times
- do not assume local hostnames and/or that they are correctly configured
> Fix Netty tests reliability

- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/SinkConnectorPropertyFactory.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/SourceConnectorPropertyFactory.java
- tests/itests-netty-http/pom.xml
- tests/itests-netty-http/src/test/java/org/apache/camel/kafkaconnector/nettyhttp/sink/CamelNettyhttpPropertyFactory.java
- tests/itests-netty-http/src/test/java/org/apache/camel/kafkaconnector/nettyhttp/sink/CamelSinkNettyhttpITCase.java
- tests/itests-netty-http/src/test/java/org/apache/camel/kafkaconnector/nettyhttp/source/CamelNettyhttpPropertyFactory.java
- tests/itests-netty-http/src/test/java/org/apache/camel/kafkaconnector/nettyhttp/source/CamelSourceNettyhttpITCase.java
- tests/itests-parent/pom.xml
- tests/pom.xml
netty-http source itests are disabled due to #969. It is reproduced but not able to find a fix yet.
> Add netty-http itests #1036

- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/utils/NetworkUtils.java
(cherry picked from commit b4282c88b91f5432e647696711c07e61812e7e16)
> NetworkUtils should be able to hold a free port for later usage #1109

- tests/itests-google-pubsub/src/test/java/org/apache/camel/kafkaconnector/google/pubsub/sink/CamelSinkGooglePubSubITCase.java
As noted on #1086 it was failing due to incorrect setting of the
endpoint.
> Re-enabled Google pub/sub test

- docs/modules/ROOT/pages/contributor-guide/troubleshooting.adoc
- examples/CamelFileSinkConnector.properties
- tests/itests-file/src/test/java/org/apache/camel/kafkaconnector/file/sink/CamelFilePropertyFactory.java
- tests/itests-file/src/test/java/org/apache/camel/kafkaconnector/file/sink/CamelSinkFileAppendCharsITCase.java
- tests/itests-file/src/test/java/org/apache/camel/kafkaconnector/file/sink/CamelSinkFileAppendITCase.java
- tests/itests-file/src/test/java/org/apache/camel/kafkaconnector/file/sink/util/CustomProducer.java
- tests/itests-file/src/test/java/org/apache/camel/kafkaconnector/file/sink/util/FileTestUtil.java
- documentation updates
- additional test cases 
- updated example 
This is related to the edge case discussed on GH issue #1208
> Camel File Sink Connector: updates

- README.adoc
https://github.com/apache/camel-kafka-connector/blob/main/docs/modules/ROOT/pages/getting-started.adoc - 404
Is this the intended link? 
https://github.com/apache/camel-kafka-connector/blob/main/docs/modules/ROOT/pages/user-guide/index.adoc
> README - fix link to 'getting started guide'

- tooling/camel-kafka-connector-generator-maven-plugin/src/test/java/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojoIT.java
Caused by commit 281fc53d7a65455dafffec7bc2170aff22a1922b
Sorry, I finally have found time to revisit the Maven IT issue. I think this fixes it.
@djencks Just FYI, sometimes changes to the Maven plugin cause an error to the daily Maven IT CI. It'd be great if we keep an eye on the results when we touch the Maven plugins. Thanks.
> Fix Maven IT failures due to doc generation removal

- connectors/antora.yml
- docs/antora.yml
- docs/modules/ROOT/pages/index.adoc
See apache/camel-website#701
Note that:
- the vote for 1.0.0 has not yet completed. Presumably it should complete before this is applied?
- This uses the Antora version 1.0.x.  I suggest we change the 0.11.x Antora version from 0.11.0 to 0.11.x similarly.
- The vote doesn't indicate this is LTS, so I said it wasn't.
> camel-website #701: RI info (1.0.x)

- connectors/antora.yml
- docs/antora.yml
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/user-guide/aggregation.adoc
See apache/camel-website#701
This does not alter the Antora version of 0.11.0, although I think it should be changed to 0.11.x.
> camel-website #701: RI info (0.11.x)

- tooling/camel-kafka-connector-catalog-descriptor-maven-plugin/pom.xml
Hi! I found the pom file of project **_org.apache.camel.kafkaconnector:camel-kafka-connector-catalog-descriptor-maven-plugin:1.1.0-SNAPSHOT_** introduced **_49_** dependencies. However, among them, **_7_** libraries (**_14%_**) are not used by your project. I list the redundant dependencies below (labelled as red ones in the figure):
org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:compile
org.sonatype.plexus:plexus-cipher:jar:1.4:compile
javax.enterprise:cdi-api:jar:1.0:compile
javax.annotation:jsr250-api:jar:1.0:compile
javax.inject:javax.inject:jar:1:compile
org.codehaus.plexus:plexus-component-annotations:jar:2.1.0:compile
org.sonatype.plexus:plexus-build-api:jar:0.0.7:compile
---
Removing the redundant dependencies can reduce the size of project and prevent potential dependency …
> Could org.apache.camel.kafkaconnector:camel-kafka-connector-catalog-descriptor-maven-plugin:1.1.0-SNAPSHOT drop off redundant dependencies?

- docs/modules/ROOT/pages/user-guide/getting-started/try-it-out-locally.adoc
Kafka uses source/sink to define source/target systems. Looks like 'sink' has been wrongly written as 'syncs' in this page.
> Updating Kafka terminology in doc
