- tests/src/test/java/org/apache/camel/kafkaconnector/sink/file/CamelSinkFileITCase.java
Prevent the file test from failing when the test file has been created but no content has been written
> Fix Sink File test

- core/pom.xml
- parent/pom.xml
- pom.xml
- tests/pom.xml
> Added release profile for the beginning

- core/pom.xml
- tests/pom.xml
> Mark camel components as provided dependencies

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkTask.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceTask.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
> Map list as headers

- core/pom.xml
- docs/try-it-out-locally.adoc
- examples/CamelCassandraQLSourceConnector.properties
- parent/pom.xml
- tests/pom.xml
> Cassandraql source example

- docs/try-it-out-locally.adoc
- examples/CamelCassandraQLSinkConnector.properties
> CassandraQL sink connector example

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceTask.java
I was reading about this today and I think our code would behave incorrectly here. 
What do you think?
Ref.: https://rules.sonarsource.com/java/RSPEC-3986
> Should use year instead of week year

- parent/pom.xml
> Bump Kafka to version 2.4.0

- tests/src/test/java/org/apache/camel/kafkaconnector/clients/cassandra/dao/TestDataDao.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/cassandra/CamelSinkCassandraITCase.java
Check for the expected amount of data in the destination table instead of just whether any data is present
> Fix issue #67: Flaky test: CamelSinkCassandraITCase

- parent/pom.xml
- tests/pom.xml
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/KafkaServiceFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/StrimziContainer.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/StrimziService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/ZookeeperContainer.java
Also updates the default Kafka service to use the containers from the Strimzi project
> Added support for testing the Kafka service using Strimzi

- core/pom.xml
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSourceTaskTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/DataFormatTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/PropertiesOrderTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/transforms/CamelTypeConverterTransformTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/utils/SchemaHelperTest.java
- parent/pom.xml
- tests/pom.xml
- tests/src/test/java/org/apache/camel/kafkaconnector/AbstractKafkaTest.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/ContainerLocalKafkaService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/KafkaService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/KafkaServiceFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/StrimziService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/KafkaConnectRunnerService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/KafkaConnectService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sns/CamelSinkAWSSNSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sqs/CamelSinkAWSSQSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/cassandra/CamelSinkCassandraITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/elasticsearch/CamelSinkElasticSearchITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/file/CamelSinkFileITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/http/CamelSinkHTTPITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/sink/jms/CamelSinkJMSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/kinesis/CamelSourceAWSKinesisITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/s3/CamelSourceAWSS3ITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/sqs/CamelSourceAWSSQSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/jms/CamelSourceJMSITCase.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/timer/CamelSourceTimerITCase.java
This resolves Github enhancement issue #74
> Migrates all the test cases to Junit 5

- docs/modules/ROOT/pages/try-it-out-on-openshift-with-strimzi.adoc
> Little updates to docs

- parent/pom.xml
- tests/pom.xml
- tests/src/test/java/org/apache/camel/kafkaconnector/AbstractKafkaTest.java
- tests/src/test/java/org/apache/camel/kafkaconnector/PluginPathHelper.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/EmbeddedKafkaService.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafka/KafkaServiceFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/DefaultKafkaConnectPropertyFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/KafkaConnectEmbedded.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/KafkaConnectRunner.java
- tests/src/test/java/org/apache/camel/kafkaconnector/services/kafkaconnect/KafkaConnectRunnerFactory.java
- tests/src/test/java/org/apache/camel/kafkaconnector/source/jms/CamelJMSPropertyFactory.java
- tests/src/test/resources/log4j2.properties
This fixes a few open issues: #24, #118 and #120
> Replaces our own connect runtime implementation with the embedded one from Kafka

- core/pom.xml
- tests/pom.xml
> Moved from camel-core to camel-core-engine as a dependecnies.

- pom.xml
- tooling/descriptors/src.xml
> Produce an assembly artifact containing all the released artifacts

- config/CamelSourceConnector.properties
- connectors/camel-aws-s3-kafka-connector/src/main/docs/camel-aws-s3-kafka-source-connector.adoc
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceConnectorConfig.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSourceTaskTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/DataFormatTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/PropertiesNameFormatsTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/PropertiesOrderTest.java
- docs/modules/ROOT/pages/connectors/camel-aws-s3-kafka-source-connector.adoc
- docs/modules/ROOT/pages/try-it-out-on-openshift-with-strimzi.adoc
- examples/CamelAWSKinesisSourceConnector.properties
- examples/CamelAWSS3SourceConnector.properties
- examples/CamelAWSSQSSourceConnector.properties
- examples/CamelCassandraQLSourceConnector.properties
- examples/CamelJmsSourceConnector.properties
- examples/CamelTelegramSourceConnector.properties
- tests/src/test/java/org/apache/camel/kafkaconnector/SourceConnectorPropertyFactory.java
> Make the topics property consistent between source and sink connectors

- docs/modules/ROOT/pages/connectors.adoc
- docs/modules/ROOT/pages/connectors/camel-syslog-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-syslog-kafka-source-connector.adoc
> Syslog docs

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkTask.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
> CamelSinkTask headers must be cleaned before sending them ahead

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkConnectorConfig.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceConnectorConfig.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
Just some minor refactoring to align with source task test layout.
> Sink test refactoring

- tests/src/test/java/org/apache/camel/kafkaconnector/sink/aws/sqs/CamelSinkAWSSQSITCase.java
- tests/testBurnInRun.sh
This should fix the test unreliability reported on #215
> Fix CamelSinkAWSSQSITCase unreliability with blocking initialization

- examples/CamelAmqpSinkConnector.properties
- examples/CamelAmqpSourceConnector.properties
Added AMQP examples for source and sink
> Add AMQP examples for source and sink

- tests/itests-aws/pom.xml
- tests/itests-cassandra/pom.xml
- tests/itests-common/src/test/resources/log4j2.properties
- tests/itests-parent/pom.xml
A few minor cleanups for the modularized test code
> Test modularization cleanups

- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojo.java
> Fixed component exclusion in combination with filter

- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/clients/dao/TestDataDao.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/clients/dao/TestResultSetConversionStrategy.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/sink/CamelSinkCassandraITCase.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/source/CamelCassandraPropertyFactory.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/source/CamelSourceCassandraITCase.java
- Adds test for the source connector
- Minor timeout fix for the sink connector test
> Cassandra test improvements

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkConnectorConfig.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkTask.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceTask.java
- core/src/main/java/org/apache/camel/kafkaconnector/aggregator/StringAggregator.java
- core/src/main/java/org/apache/camel/kafkaconnector/utils/CamelMainSupport.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/DataFormatTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/utils/SampleAggregator.java
> Aggregate Support

- pom.xml
- tests/itests-mongodb/pom.xml
> Fixes camel-dependencies to point to 3.4.0

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkConnectorConfig.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkTask.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceTask.java
- core/src/main/java/org/apache/camel/kafkaconnector/utils/CamelMainSupport.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/DataFormatTest.java
> Added Aggregation timeout

- parent/pom.xml
- tests/itests-cassandra/pom.xml
> Upgrade Kafka to version 2.5.0

- README.adoc
Added additional explanation about testing for HDFS, MongoDB, Salesforce and Slack.
> Added additional explanation about testing 

- parent/pom.xml
- pom.xml
> Bump Camel to version 3.4.2

- docs/modules/ROOT/pages/aggregation.adoc
- docs/modules/ROOT/pages/index.adoc
> Added Aggregation documentation

- docs/modules/ROOT/pages/aggregation.adoc
- docs/modules/ROOT/pages/archetypes.adoc
- docs/modules/ROOT/pages/index.adoc
> Archetypes docs

- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/source/CamelSourceCassandraITCase.java
Reopening this one again after fixing the problems from last time. It seems fine now.
> Re-enable a Cassandra test disabled due to CAMEL-15219

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/camel-compatibility-matrix.adoc
- docs/modules/ROOT/pages/index.adoc
> Added a camel-compatibility matrix page

- archetypes/camel-kafka-connector-extensible-archetype/src/main/resources/archetype-resources/pom.xml
> Make the camel-kafka-connector archetype use the parent POM

- tests/itests-aws-common/src/test/java/org/apache/camel/kafkaconnector/aws/common/AWSCommon.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/clients/AWSClientUtils.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/common/AWSCommon.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/kinesis/source/CamelSourceAWSKinesisITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/s3/source/CamelSourceAWSS3ITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sns/sink/CamelSinkAWSSNSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/sink/CamelSinkAWSSQSITCase.java
- tests/itests-aws-v1/src/test/java/org/apache/camel/kafkaconnector/aws/v1/sqs/source/CamelSourceAWSSQSITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/kinesis/source/CamelSourceAWSKinesisITCase.java
Just a small set of cleanups in order to make subsequent AWS tests clearer
> Minor AWS tests cleanups

- core/src/main/java/org/apache/camel/kafkaconnector/utils/CamelMainSupport.java
I wasn't sure if that was intentional or not, so sending it as a quick fix just in case
> Added missing fromUrl to the log message

- connectors/camel-aws-s3-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/awss3/serializers/S3ObjectSerializer.java
- connectors/camel-aws2-s3-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2s3/serializers/S3ObjectSerializer.java
Just a minor logging fix ... similar to #372
> Fixed incorrect number of log arguments in S3 exception handling

- docs/modules/ROOT/pages/try-it-out-on-kubernetes.adoc
> #389 - Fix doc- Kubernetes command

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceTask.java
> Support Multiple topics on Source Connector

- connectors/camel-sjms2-kafka-connector/src/main/docs/camel-sjms2-kafka-sink-connector.adoc
- connectors/camel-sjms2-kafka-connector/src/main/docs/camel-sjms2-kafka-source-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-sjms2-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-sjms2-kafka-source-connector.adoc
> Activemq-all note for SJMS2 connector

- README.adoc
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/testing.adoc
Marking as draft to collect some feedback
> Rework the testing documentation and adds test writing details

- tests/itests-jdbc/src/test/java/org/apache/camel/kafkaconnector/jdbc/client/DatabaseClient.java
> Fix potentially unreleased DB resources in test code

- connectors/camel-aws-s3-kafka-connector/src/main/docs/camel-aws-s3-kafka-sink-connector.adoc
- connectors/camel-aws-s3-kafka-connector/src/main/docs/camel-aws-s3-kafka-source-connector.adoc
- connectors/camel-aws-s3-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/awss3/transformers/S3ObjectTransformer.java
- connectors/camel-aws2-s3-kafka-connector/src/main/docs/camel-aws2-s3-kafka-sink-connector.adoc
- connectors/camel-aws2-s3-kafka-connector/src/main/docs/camel-aws2-s3-kafka-source-connector.adoc
- connectors/camel-aws2-s3-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2s3/transformers/S3ObjectTransformers.java
- connectors/camel-aws2-sqs-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2sqs/transformers/SQSKeySetterTransformers.java
- docs/modules/ROOT/pages/connectors/camel-aws-s3-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-aws-s3-kafka-source-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-aws2-s3-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-aws2-s3-kafka-source-connector.adoc
> Transformers package renaming

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkConnectorConfig.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
> Support for topics.regex

- docs/modules/ROOT/pages/try-it-out-locally.adoc
Change in keyword "comand" to "command"
> Document Update

- tests/itests-aws-v2/pom.xml
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/clients/AWSSDKClientUtils.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/source/CamelAWSS3PropertyFactory.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/source/CamelSourceAWSS3ITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/source/TestS3Configuration.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/services/AWSS3LocalContainerService.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/services/AWSServiceFactory.java
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file0.test
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file1.test
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file2.test
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file3.test
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file4.test
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file5.test
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file6.test
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file7.test
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file8.test
- tests/itests-aws-v2/src/test/resources/org/apache/camel/kafkaconnector/aws/v2/s3/source/file9.test
Trying this one again after (probably) fixing the issues from the previous attempt.
> Added AWS S3 test using AWS v2

- .github/workflows/automatic-changelog-update.yml
Thanks to @christophd for reporting this.
> Fixes changelog to run only on master

- .github/asf-deploy-settings.xml
- .github/workflows/asf-snapshots-deploy.yml
> Deploy on ASF Snapshot

- core/src/main/java/org/apache/camel/kafkaconnector/utils/CamelMainSupport.java
> [camel-main-support] Reordering props should not be required anymore

- docs/modules/ROOT/pages/try-it-out-on-kubernetes.adoc
@valdar please review this
this is from our conversation on zulip chat. 
[Here's a link to our conversation for your reference](https://camel.zulipchat.com/#narrow/stream/257303-camel-kafka-connector/topic/K8s.20liveness.20probe)
Please give me some suggestions to write it a bit better :)
> adding docs that explain the directory requirement under the plugins folder

- core/src/main/java/org/apache/camel/kafkaconnector/utils/CamelKafkaConnectMain.java
- core/src/main/java/org/apache/camel/kafkaconnector/utils/CamelMainSupport.java
> [camel-main-support] Use BaseMainSupport instead of Main

- docs/modules/ROOT/pages/contributing.adoc
Basic documentation covering the item on #513
> Added build details using mvnd

- tooling/camel-kafka-connector-catalog-descriptor-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/catalog/descriptor/CollectConnectorDescriptorMojo.java
> Improve Catalog and cleanup

- core/src/main/java/org/apache/camel/kafkaconnector/CamelConnectorUtils.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkTask.java
- core/src/main/java/org/apache/camel/kafkaconnector/CamelSourceTask.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSourceTaskTest.java
> source: better handling of headers of type Data

- core/src/main/java/org/apache/camel/kafkaconnector/utils/CamelKafkaConnectMain.java
- core/src/test/java/org/apache/camel/kafkaconnector/DataFormatTest.java
> Camel 3.6 features

- tooling/camel-kafka-connector-generator-maven-plugin/README.adoc
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/utils/MavenUtils.java
Add readme text for the maven plugin and don't overwrite class if it is missing the @Generated string.
> ISSUE-146 Prevent the overwrite of existing classes unless they are @Generated annotated

- distribution/pom.xml
- distribution/src/main/assemblies/repository.xml
- distribution/src/main/assemblies/source-release.xml
- pom.xml
https://github.com/apache/camel-kafka-connector/issues/524
> ISSUE-524 Create a source distribution module

- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-aws-s3-sink.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-aws-s3-source.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-aws2-s3-sink.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-aws2-s3-source.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-aws2-sqs-sink.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-aws2-sqs-source.json
- camel-kafka-connector-catalog/src/test/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalogTest.java
- connectors/camel-aws-s3-kafka-connector/src/generated/resources/camel-aws-s3-sink.json
- connectors/camel-aws-s3-kafka-connector/src/generated/resources/camel-aws-s3-source.json
- connectors/camel-aws-s3-kafka-connector/src/main/docs/camel-aws-s3-kafka-sink-connector.adoc
- connectors/camel-aws-s3-kafka-connector/src/main/docs/camel-aws-s3-kafka-source-connector.adoc
- connectors/camel-aws-s3-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/awss3/transformers/S3ObjectTransforms.java
- connectors/camel-aws2-s3-kafka-connector/src/generated/resources/camel-aws2-s3-sink.json
- connectors/camel-aws2-s3-kafka-connector/src/generated/resources/camel-aws2-s3-source.json
- connectors/camel-aws2-s3-kafka-connector/src/main/docs/camel-aws2-s3-kafka-sink-connector.adoc
- connectors/camel-aws2-s3-kafka-connector/src/main/docs/camel-aws2-s3-kafka-source-connector.adoc
- connectors/camel-aws2-s3-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2s3/transformers/S3ObjectTransforms.java
- connectors/camel-aws2-sqs-kafka-connector/src/generated/resources/camel-aws2-sqs-sink.json
- connectors/camel-aws2-sqs-kafka-connector/src/generated/resources/camel-aws2-sqs-source.json
- connectors/camel-aws2-sqs-kafka-connector/src/main/docs/camel-aws2-sqs-kafka-sink-connector.adoc
- connectors/camel-aws2-sqs-kafka-connector/src/main/docs/camel-aws2-sqs-kafka-source-connector.adoc
- connectors/camel-aws2-sqs-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2sqs/transformers/SQSKeySetterTransforms.java
- docs/modules/ROOT/pages/connectors/camel-aws-s3-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-aws-s3-kafka-source-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-aws2-s3-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-aws2-s3-kafka-source-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-aws2-sqs-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-aws2-sqs-kafka-source-connector.adoc
> Rename all transformers, converters, aggregationStrategies to reflect the maning convention we have

- camel-kafka-connector-catalog/src/test/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalogTest.java
> Swap arguments so they are in the correct order: expected value, actual

- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-elasticsearch-rest-sink.json
- connectors/camel-elasticsearch-rest-kafka-connector/src/generated/resources/camel-elasticsearch-rest-sink.json
- connectors/camel-elasticsearch-rest-kafka-connector/src/main/docs/camel-elasticsearch-rest-kafka-sink-connector.adoc
- connectors/camel-elasticsearch-rest-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/elasticsearchrest/transformers/ConnectRecordValueToMapTransforms.java
- docs/modules/ROOT/pages/connectors/camel-elasticsearch-rest-kafka-sink-connector.adoc
- tests/itests-elasticsearch/src/test/java/org/apache/camel/kafkaconnector/elasticsearch/sink/CamelSinkElasticSearchITCase.java
> Move ConnectRecordValueToMapTransformer of Elastisearch IT test in the connector

- camel-kafka-connector-catalog/src/main/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalog.java
- camel-kafka-connector-catalog/src/test/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalogTest.java
> Added convenience method to get option from connector name and option name

- archetypes/camel-kafka-connector-extensible-apicurio-archetype/pom.xml
- archetypes/camel-kafka-connector-extensible-apicurio-archetype/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
- archetypes/camel-kafka-connector-extensible-apicurio-archetype/src/main/resources/META-INF/LICENSE.txt
- archetypes/camel-kafka-connector-extensible-apicurio-archetype/src/main/resources/META-INF/NOTICE.txt
- archetypes/camel-kafka-connector-extensible-apicurio-archetype/src/main/resources/archetype-resources/ReadMe.txt
- archetypes/camel-kafka-connector-extensible-apicurio-archetype/src/main/resources/archetype-resources/pom.xml
- archetypes/camel-kafka-connector-extensible-apicurio-archetype/src/main/resources/archetype-resources/src/main/assembly/package.xml
- archetypes/camel-kafka-connector-extensible-apicurio-archetype/src/test/resources/projects/camel-timer-kafka-connector/archetype.properties
- archetypes/camel-kafka-connector-extensible-apicurio-archetype/src/test/resources/projects/camel-timer-kafka-connector/goal.txt
- archetypes/pom.xml
- parent/pom.xml
> Provide an archetype with needed bits to use Apicurio Registry stuff

- archetypes/camel-kafka-connector-extensible-dataformat-archetype/pom.xml
- archetypes/camel-kafka-connector-extensible-dataformat-archetype/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
- archetypes/camel-kafka-connector-extensible-dataformat-archetype/src/main/resources/META-INF/LICENSE.txt
- archetypes/camel-kafka-connector-extensible-dataformat-archetype/src/main/resources/META-INF/NOTICE.txt
- archetypes/camel-kafka-connector-extensible-dataformat-archetype/src/main/resources/archetype-resources/ReadMe.txt
- archetypes/camel-kafka-connector-extensible-dataformat-archetype/src/main/resources/archetype-resources/pom.xml
- archetypes/camel-kafka-connector-extensible-dataformat-archetype/src/main/resources/archetype-resources/src/main/assembly/package.xml
- archetypes/camel-kafka-connector-extensible-dataformat-archetype/src/test/resources/projects/camel-timer-kafka-connector/archetype.properties
- archetypes/camel-kafka-connector-extensible-dataformat-archetype/src/test/resources/projects/camel-timer-kafka-connector/goal.txt
- archetypes/pom.xml
> Added a dataformat archetype for extending connectors

- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/CamelKafkaConnectorUpdateMojo.java
> Remove unused private code

- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/CamelKafkaConnectorUpdateMojo.java
> Use genericity to simplify code in CamelKafkaConnectorUpdateMojo

- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/clients/JMSClient.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/services/ArtemisContainer.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/services/ContainerLocalService.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/services/JMSContainer.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/services/JMSService.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/services/QpidDispatchRouterContainer.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/services/RemoteJMSService.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/sink/CamelSinkJMSITCase.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/source/CamelSourceJMSITCase.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/source/CamelSourceJMSWithAggregation.java
- Initialize at the correct callback
- Decouple the client from the services
> Minor SJMS2 test cleanups

- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-sftp-sink.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-sftp-source.json
- connectors/camel-sftp-kafka-connector/src/generated/resources/camel-sftp-sink.json
- connectors/camel-sftp-kafka-connector/src/generated/resources/camel-sftp-source.json
- connectors/camel-sftp-kafka-connector/src/main/docs/camel-sftp-kafka-sink-connector.adoc
- connectors/camel-sftp-kafka-connector/src/main/docs/camel-sftp-kafka-source-connector.adoc
- connectors/camel-sftp-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/sftp/transformers/SftpRemoteFileTransforms.java
- docs/modules/ROOT/pages/connectors.adoc
- docs/modules/ROOT/pages/connectors/camel-sftp-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-sftp-kafka-source-connector.adoc
> SFTP connector: add RemoteFileTransform

- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/source/CamelSourceAWSS3ITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sqs/sink/CamelSinkAWSSQSITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sqs/source/CamelSourceAWSSQSITCase.java
- re-enable a few tests
- add extra debug information
> AWS v2 tests tweaks

- archetypes/camel-kafka-connector-extensible-apicurio-archetype/src/main/resources/archetype-resources/pom.xml
> Review Archetype generation after new dependencies added to core

- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-ftps-sink.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-ftps-source.json
- connectors/camel-ftps-kafka-connector/src/generated/resources/camel-ftps-sink.json
- connectors/camel-ftps-kafka-connector/src/generated/resources/camel-ftps-source.json
- connectors/camel-ftps-kafka-connector/src/main/docs/camel-ftps-kafka-sink-connector.adoc
- connectors/camel-ftps-kafka-connector/src/main/docs/camel-ftps-kafka-source-connector.adoc
- connectors/camel-ftps-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/ftps/transformers/FtpsRemoteFileTransforms.java
- docs/modules/ROOT/pages/connectors/camel-ftps-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-ftps-kafka-source-connector.adoc
> Add RemoteFileTransforms to the FTPS connector directly

- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-ftp-sink.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-ftp-source.json
- connectors/camel-ftp-kafka-connector/src/generated/resources/camel-ftp-sink.json
- connectors/camel-ftp-kafka-connector/src/generated/resources/camel-ftp-source.json
- connectors/camel-ftp-kafka-connector/src/main/docs/camel-ftp-kafka-sink-connector.adoc
- connectors/camel-ftp-kafka-connector/src/main/docs/camel-ftp-kafka-source-connector.adoc
- connectors/camel-ftp-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/ftp/transformers/FtpRemoteFileTransforms.java
- docs/modules/ROOT/pages/connectors/camel-ftp-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-ftp-kafka-source-connector.adoc
> Add RemoteFileTransforms to the FTP connector directly 

- tests/itests-sql/pom.xml
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/client/DatabaseClient.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/services/SQLLocalContainerService.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/services/SQLRemoteService.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/services/SQLService.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/services/SQLServiceFactory.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/services/TestDataSource.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/sink/CamelSinkSQLITCase.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/sink/CamelSqlPropertyFactory.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/source/CamelSourceSQLITCase.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/source/CamelSqlPropertyFactory.java
- tests/itests-sql/src/test/resources/schema.sql
- tests/pom.xml
> Camel-SQL Kafka Connector Added integration tests

- tooling/camel-kafka-connector-catalog-descriptor-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/catalog/descriptor/CollectConnectorDescriptorMojo.java
> Factorize code in CollectConnectorDescriptorMojo

- parent/pom.xml
- pom.xml
@orpiske @valdar with this we should be done for releasing 3.7.0
> Camel-Master updated to 3.7.0 staging

- docs/modules/ROOT/pages/try-it-out-on-kubernetes.adoc
Fixed an error with Strimzi release variable. Small improvements to the command line procedure.
> Update try-it-out-on-kubernetes procedure

- core/src/main/java/org/apache/camel/kafkaconnector/utils/CamelKafkaConnectMain.java
Beware: it also bumps camel dependency to ~3.7.1-SNAPSHOT~ 3.8.0-SNAPSHOT due to requiring apache/camel#4834
For 3.7.x, we'll depend on the backport pushed to apache/camel#4835.
> Fix issue #159: camel components secret options are showed in logs

- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/clients/dao/TestDataDao.java
Trying to fix Apache CI issues when running the CQL tests ...
> Create timeout when creating Cassandra's test table

- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/sink/CamelJMSPropertyFactory.java
This should do the trick for issue #844
> Avoid slashes in sjms2 URLs

- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-github-sink.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-github-source.json
- connectors/camel-github-kafka-connector/src/generated/resources/camel-github-sink.json
- connectors/camel-github-kafka-connector/src/generated/resources/camel-github-source.json
- connectors/camel-github-kafka-connector/src/main/docs/camel-github-kafka-sink-connector.adoc
- connectors/camel-github-kafka-connector/src/main/docs/camel-github-kafka-source-connector.adoc
- connectors/camel-github-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/github/transformers/EventTypeTransforms.java
- docs/modules/ROOT/pages/connectors/camel-github-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-github-kafka-source-connector.adoc
> Added an EventTypeTransforms to Github Source connector

- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/source/CamelSourceAWSS3ITCase.java
- tests/itests-azure-storage-blob/src/test/java/org/apache/camel/kafkaconnector/azure/storage/blob/sink/CamelSinkAzureStorageBlobITCase.java
- tests/itests-azure-storage-queue/src/test/java/org/apache/camel/kafkaconnector/azure/storage/queue/sink/CamelSinkAzureStorageQueueITCase.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/BasicConnectorPropertyFactory.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/PluginPathHelper.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/clients/kafka/KafkaClient.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafka/EmbeddedKafkaService.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafkaconnect/KafkaConnectRunner.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafkaconnect/KafkaConnectRunnerService.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/services/kafkaconnect/KafkaConnectService.java
- tests/itests-elasticsearch/src/test/java/org/apache/camel/kafkaconnector/elasticsearch/sink/CamelSinkElasticSearchITCase.java
- tests/itests-hdfs/src/test/java/org/apache/camel/kafkaconnector/hdfs/sink/CamelSinkHDFSITCase.java
- tests/itests-jdbc/src/test/java/org/apache/camel/kafkaconnector/jdbc/client/DatabaseClient.java
- tests/itests-jdbc/src/test/java/org/apache/camel/kafkaconnector/jdbc/sink/CamelSinkJDBCITCase.java
- tests/itests-jdbc/src/test/java/org/apache/camel/kafkaconnector/jdbc/sink/CamelSinkJDBCNoDataSourceITCase.java
- tests/itests-mongodb/src/test/java/org/apache/camel/kafkaconnector/mongodb/sink/CamelSinkMongoDBITCase.java
- tests/itests-rabbitmq/src/test/java/org/apache/camel/kafkaconnector/rabbitmq/clients/RabbitMQClient.java
- tests/itests-rabbitmq/src/test/java/org/apache/camel/kafkaconnector/rabbitmq/sink/RabbitMQSinkITCase.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/client/DatabaseClient.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/sink/CamelSinkSQLITCase.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/source/CamelSourceSQLITCase.java
- tests/itests-ssh/src/test/java/org/apache/camel/kafkaconnector/ssh/services/SshService.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/services/SyslogService.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/source/CamelSourceSyslogITCase.java
Lots of small / 1-line cleanups in the test code base
> Test cleanups

- parent/pom.xml
- tests/itests-hdfs/src/test/java/org/apache/camel/kafkaconnector/hdfs/sink/CamelSinkHDFSITCase.java
> Bump to Kafka 2.7.0

- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-aws2-kinesis-sink.json
- camel-kafka-connector-catalog/src/generated/resources/connectors/camel-aws2-kinesis-source.json
- connectors/camel-aws2-kinesis-kafka-connector/src/generated/resources/camel-aws2-kinesis-sink.json
- connectors/camel-aws2-kinesis-kafka-connector/src/generated/resources/camel-aws2-kinesis-source.json
- connectors/camel-aws2-kinesis-kafka-connector/src/main/docs/camel-aws2-kinesis-kafka-sink-connector.adoc
- connectors/camel-aws2-kinesis-kafka-connector/src/main/docs/camel-aws2-kinesis-kafka-source-connector.adoc
- connectors/camel-aws2-kinesis-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2kinesis/transformers/KinesisRecordDataTransforms.java
- docs/modules/ROOT/pages/connectors/camel-aws2-kinesis-kafka-sink-connector.adoc
- docs/modules/ROOT/pages/connectors/camel-aws2-kinesis-kafka-source-connector.adoc
> AWS2-Kinesis SMT for extracting data

- parent/pom.xml
> Upgrade Strimzi to version 0.21.0.kafka-2.7.0

- parent/pom.xml
> Bump Apicurio Registry to version 1.3.2.Final

- tests/itests-hdfs/pom.xml
- tests/itests-hdfs/src/test/java/org/apache/camel/kafkaconnector/hdfs/sink/CamelSinkHDFSITCase.java
FYI: it's likely we'll have to do the same for the connector deps, but I'll need more time to verify it. I'll send a separate PR for that, if it's the case.
> Fix HDFS tests incompatibilities

- docs/modules/ROOT/pages/camel-compatibility-matrix.adoc
> Add a column to compatibility matrix about Kafka version

- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/AbstractCamelKafkaConnectorMojo.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/CamelKafkaConnectorDeleteMojo.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojo.java
https://github.com/apache/camel-kafka-connector/issues/149
> Provide option to delete camel kafka submodule if they are not in camel catalog

- README.adoc
Reverts apache/camel-kafka-connector#965
> Revert "Test PR"

- parent/pom.xml
Please don't merge yet. POC for GH issue #990
> Override Camel's testcontainer version and upgrade to 1.15.1 due to GH issue #990

- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/kinesis/source/CamelSourceAWSKinesisITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/common/S3Utils.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/source/CamelSourceAWSS3LargeFilesITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sqs/source/CamelSourceAWSSQSITCase.java
- tests/itests-azure-storage-queue/src/test/java/org/apache/camel/kafkaconnector/azure/storage/queue/source/CamelSourceAzureStorageQueueITCase.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/source/CamelSourceCassandraITCase.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/AbstractTestMessageConsumer.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/CamelSourceTestSupport.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/IntegerMessageConsumer.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/StringMessageConsumer.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/TestMessageConsumer.java
- tests/itests-mongodb/src/test/java/org/apache/camel/kafkaconnector/mongodb/source/CamelSourceMongoDBITCase.java
- tests/itests-rabbitmq/src/test/java/org/apache/camel/kafkaconnector/rabbitmq/source/RabbitMQSourceITCase.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/source/CamelSourceJMSITCase.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/source/CamelSourceJMSWithAggregation.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/source/CamelSourceSQLITCase.java
- tests/itests-ssh/src/test/java/org/apache/camel/kafkaconnector/ssh/sink/CamelSinkSshITCase.java
- tests/itests-ssh/src/test/java/org/apache/camel/kafkaconnector/ssh/source/CamelSourceSshITCase.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/source/CamelSourceSyslogITCase.java
- tests/itests-timer/src/test/java/org/apache/camel/kafkaconnector/timer/source/CamelSourceTimerITCase.java
Reuse common test code for source tests in most of the cases
> Cleanup all source integration tests

- tooling/camel-kafka-connector-generator-maven-plugin/src/main/resources/camel-kafka-connector-sink-options.mvel
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/resources/camel-kafka-connector-source-options.mvel
> Improve description of connector in documentation

- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/ec2/sink/CamelSinkAWSEC2ITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/iam/sink/CamelSinkAWSIAMITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/kinesis/sink/CamelSinkAWSKinesisITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/kinesis/source/CamelSourceAWSKinesisITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/common/S3Utils.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/sink/CamelSinkAWSS3ITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/source/CamelSourceAWSS3LargeFilesITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sqs/source/CamelSourceAWSSQSITCase.java
- tests/itests-azure-storage-blob/src/test/java/org/apache/camel/kafkaconnector/azure/storage/blob/sink/CamelSinkAzureStorageBlobITCase.java
- tests/itests-azure-storage-queue/src/test/java/org/apache/camel/kafkaconnector/azure/storage/queue/sink/CamelSinkAzureStorageQueueITCase.java
- tests/itests-azure-storage-queue/src/test/java/org/apache/camel/kafkaconnector/azure/storage/queue/source/CamelSourceAzureStorageQueueITCase.java
- tests/itests-cassandra/src/test/java/org/apache/camel/kafkaconnector/cassandra/source/CamelSourceCassandraITCase.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/AbstractTestMessageConsumer.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/CamelSourceTestSupport.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/IntegerMessageConsumer.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/StringMessageConsumer.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/TestMessageConsumer.java
- tests/itests-mongodb/src/test/java/org/apache/camel/kafkaconnector/mongodb/source/CamelSourceMongoDBITCase.java
- tests/itests-rabbitmq/src/test/java/org/apache/camel/kafkaconnector/rabbitmq/source/RabbitMQSourceITCase.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/source/CamelSourceJMSITCase.java
- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/source/CamelSourceJMSWithAggregation.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/source/CamelSourceSQLITCase.java
- tests/itests-ssh/src/test/java/org/apache/camel/kafkaconnector/ssh/sink/CamelSinkSshITCase.java
- tests/itests-ssh/src/test/java/org/apache/camel/kafkaconnector/ssh/source/CamelSourceSshITCase.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/source/CamelSourceSyslogITCase.java
- tests/itests-timer/src/test/java/org/apache/camel/kafkaconnector/timer/source/CamelSourceTimerITCase.java
Contains disabled tests due to #997 and a few other issues happening only on Camel Master build
> Backport source test improvements and fixes

- tests/itests-sjms2/src/test/java/org/apache/camel/kafkaconnector/sjms2/sink/CamelSinkJMSStartupITCase.java
This reverts commit 61fab4984b78eae9102373e37bf137c9915410fa.
> Revert "Temporarily disabled a error handling test for SJMS2 due to failures on GH actions"

- tests/itests-aws-v2/pom.xml
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sns/sink/CamelAWSSNSPropertyFactory.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sns/sink/CamelSinkAWSSNSITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/sns/sink/TestSnsConfiguration.java
> (backport) Added AWS v2 SNS sink integration test

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/remove-headers.adoc
> Remove headers docs

- .github/workflows/maven-it.yaml
> Add gh action for daily maven plugins IT

- docs/modules/ROOT/pages/connectors.adoc
- tooling/camel-kafka-connector-catalog-descriptor-maven-plugin/src/main/resources/connectors.mvel
- tooling/camel-kafka-connector-docs-maven-plugin/src/main/resources/connectors.mvel
> Website: connectors' list formatting problems

- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/CamelSourceTestSupport.java
- tests/itests-netty/pom.xml
- tests/itests-netty/src/test/java/org/apache/camel/kafkaconnector/netty/source/CamelNettyPropertyFactory.java
- tests/itests-netty/src/test/java/org/apache/camel/kafkaconnector/netty/source/CamelSourceNettyITCase.java
- tests/pom.xml
First part - camel-netty-kafka-connector source itest.
Will follow up with other itests later.
> Add Netty source itest #1036

- tests/itests-couchbase/src/test/java/org/apache/camel/kafkaconnector/couchbase/sink/CamelSinkCouchbaseITCase.java
> Re-enables the basic test for couchbase since it was fixed on CAMEL-16284

- core/src/main/java/org/apache/camel/kafkaconnector/transforms/SinkPojoToSchemaAndStructTransform.java
- tests/itests-aws-v2/pom.xml
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/lambda/sink/CamelAWSLambdaPropertyFactory.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/lambda/sink/CamelSinkLambdaITCase.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/lambda/sink/TestLambda2Configuration.java
- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/s3/sink/CamelSinkAWSS3ITCase.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/clients/kafka/ByteProducerPropertyFactory.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/clients/kafka/KafkaClient.java
- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/AbstractTestMessageProducer.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/sink/CamelSinkSQLITCase.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/source/CamelSourceSyslogITCase.java
- tooling/camel-kafka-connector-docs-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/docs/UpdateDocComponentsListMojo.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/CamelKafkaConnectorCreateMojo.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/CamelKafkaConnectorUpdateMojo.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojo.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/utils/JsonMapperKafkaConnector.java
- tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/utils/MavenUtils.java
Second set of fixes and cleanups from camel-master
> Refresh to master fixes that were lying on camel-master (pt 2)

- tests/itests-common/src/test/java/org/apache/camel/kafkaconnector/common/test/CamelSourceTestSupport.java
- tests/itests-netty/pom.xml
- tests/itests-netty/src/test/java/org/apache/camel/kafkaconnector/netty/sink/CamelNettyPropertyFactory.java
- tests/itests-netty/src/test/java/org/apache/camel/kafkaconnector/netty/sink/CamelSinkNettyITCase.java
- tests/itests-netty/src/test/java/org/apache/camel/kafkaconnector/netty/source/CamelNettyPropertyFactory.java
- tests/itests-netty/src/test/java/org/apache/camel/kafkaconnector/netty/source/CamelSourceNettyITCase.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/sink/CamelSyslogPropertyFactory.java
- tests/itests-syslog/src/test/java/org/apache/camel/kafkaconnector/syslog/source/CamelSyslogPropertyFactory.java
- tests/pom.xml
As discussed w/ @oscerd, this supersedes #1072
> Backport Netty tests + fixes

- parent/pom.xml
> Upgrade Strimzi to version 0.22.1

- tests/itests-azure-storage-blob/pom.xml
> Work around Jackson conflicts for the azure-storage-blob tests

- parent/pom.xml
> Kafka 2.8.0 and Strimzi

- parent/pom.xml
> Upgrade to Strimzi 0.23.0

- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/kinesis/common/KinesisUtils.java
AWS2 Kinesis Sink test was failing because the shard was not available
at the time the check was occurring
> Fix AWS2 Kinesis Sink issues

- tests/itests-aws-v2/src/test/java/org/apache/camel/kafkaconnector/aws/v2/cw/sink/CamelSinkAWSCWITCase.java
Dimensions are not working correctly in LocalStack's implementation of cloud watch in LocalStack 0.12.10. This forces the test to use 0.12.9.1
> Fix AWS2 Cloud Watch test issues due to LocalStack bug

- parent/pom.xml
> Upgrade to Strimzi 0.24.0

- parent/pom.xml
> Upgrade Strimzi to version 0.25.0

- docs/indexPages.yml
- docs/local-build.sh
- docs/source-map.yml
- docs/source-watch.yml
This sets up the local/partial build structure for ckc and prepares for moving the playbook config for the page generation to a local file.
(main branch)
> Main local index page and local/partial build

- docs/README_local_build.adoc
- docs/local-build.sh
- docs/source-watch.yml
Sets up new docs local-build for camel-kaka-connector main. See apache/camel-website#731
> update to docs local build v2

- docs/README_local_build.adoc
- docs/local-build.sh
- docs/source-watch.yml
Sets up new docs local-build for camel-kaka-connector 0.11.x. See apache/camel-website#731
> Camel kafka connector 0.11.x local build v2

- connectors/antora.yml
- docs/antora.yml
- docs/modules/ROOT/pages/index.adoc
See https://github.com/apache/camel-website/issues/701
> camel-website #701: RI info (main)

- docs/modules/ROOT/examples/js/ckc.js
- docs/modules/ROOT/pages/index.adoc
> camel-website #701 camel-kafka-connector RI table improvement (main)

- docs/modules/ROOT/examples/js/ckc.js
- docs/modules/ROOT/pages/index.adoc
> camel-website #701 camel-kafka-connector RI table improvement (1.0.x)

- docs/modules/ROOT/examples/js/ckc.js
- docs/modules/ROOT/pages/index.adoc
> camel-website #701 camel-kafka-connector RI table improvement (0.11.x)

- parent/pom.xml
- tests/itests-jdbc/src/test/java/org/apache/camel/kafkaconnector/jdbc/sink/CamelSinkJDBCITCase.java
- tests/itests-jdbc/src/test/java/org/apache/camel/kafkaconnector/jdbc/sink/CamelSinkJDBCNoDataSourceITCase.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/sink/CamelSinkSQLITCase.java
- tests/itests-sql/src/test/java/org/apache/camel/kafkaconnector/sql/source/CamelSourceSQLITCase.java
- Align test containers version with the same one used by Camel Core
- Fix test issues on Apple Silicon
> (chores) Multiple test fixes and improvements

- .github/workflows/maven-it.yaml
To get faster feedback for any impact on the Maven plugin.
> Change Maven IT CI from daily to per pull request

- core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkTask.java
- core/src/test/java/org/apache/camel/kafkaconnector/CamelSinkTaskTest.java
- parent/pom.xml
Fixed handling `SinkRecord` headers without schema.
> fix #1447 Fixed NPE error during SinkTask header mapping

- docs/modules/ROOT/pages/reference/transformers/fieldsToHeaders.adoc
Fix the capitalisation of FieldsToHeadersTransform configuration
> Fix capitalisation

- docs/modules/ROOT/pages/contributor-guide/release-guide.adoc
- release-utils/scripts/promote-release.sh
- release-utils/scripts/sign.sh
- release-utils/scripts/upload-source.sh
> Added release automation for dist/dev svn and SBOM
